// Photography Portfolio — Photo Data
// Design: "Fog & Field" Nordic Atmospheric Minimalism
// All CDN URLs for the 25 uploaded photographs

export interface Photo {
  id: string;
  src: string;
  title: string;
  category: string;
  season: string;
  mood: string;
  description: string;
  orientation: "landscape" | "portrait" | "square";
  featured?: boolean;
}

export const photos: Photo[] = [
  {
    id: "IMG_7274",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/wVWzLtIZKirqXoGB.jpg",
    title: "Solitude on Still Water",
    category: "Wildlife",
    season: "Winter",
    mood: "Minimalist",
    description: "A lone white bird drifts across a fog-shrouded lake, surrounded by the ghostly silhouettes of submerged dead trees reflected in the glassy surface.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_9755",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/hCZltdzYEfqikrIS.jpg",
    title: "The Vast Beyond",
    category: "Landscape",
    season: "Summer",
    mood: "Epic",
    description: "A lone hiker stands at the edge of a mountain summit, dwarfed by a panoramic sweep of rolling hills and a dramatic cloud-filled sky.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_3240",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/BvLyvcSFYBQBeiZD.jpg",
    title: "Golden River",
    category: "Landscape",
    season: "Summer",
    mood: "Warm",
    description: "A fisherman's silhouette cuts against an incandescent sunset on a river, the water transformed into liquid gold by the dying light.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_9496",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/sdIwYeqhVCbFUFRc.jpg",
    title: "Frost at Dusk",
    category: "Landscape",
    season: "Autumn",
    mood: "Dramatic",
    description: "A frost-covered hillside meadow glows amber beneath a brooding storm sky, the tension between warm earth and cold sky creating an otherworldly atmosphere.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_2084",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MkurKGZvBuwnNNxh.jpg",
    title: "Into the Mist",
    category: "Documentary",
    season: "Summer",
    mood: "Mysterious",
    description: "Two hikers — an adult and a child — walk hand in hand into a fog-filled beech forest, their small figures swallowed by the cathedral of trees.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_3176",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/PykovAntDmOnNFNj.jpg",
    title: "Heron in Flight",
    category: "Wildlife",
    season: "Summer",
    mood: "Graceful",
    description: "A grey heron glides low over a misty morning river, its wings catching the backlit glow of early sun filtering through riverside willows.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_5504",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/uHEorESBJLGARURq.jpg",
    title: "Lamplight in Snow",
    category: "Winter",
    season: "Winter",
    mood: "Romantic",
    description: "Three vintage street lanterns glow with warm amber light against the deep blue of a winter dusk, their bases buried in deep snow.",
    orientation: "landscape",
  },
  {
    id: "IMG_6088",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/gOVvcFsoGtDcPUgv.jpg",
    title: "Mountain Winter",
    category: "Landscape",
    season: "Winter",
    mood: "Majestic",
    description: "A small house nestles in a snow-covered mountain valley, the forested ridges receding into blue atmospheric haze in layers of increasing distance.",
    orientation: "portrait",
  },
  {
    id: "IMG_1797",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MmanKLaaJIZuabBQ.jpg",
    title: "Storm Over the Fields",
    category: "Landscape",
    season: "Summer",
    mood: "Dramatic",
    description: "A lone tree stands sentinel at the horizon of geometric agricultural fields as a dramatic storm sky builds above, the graphic patterns of crops creating a striking foreground.",
    orientation: "portrait",
  },
  {
    id: "IMG_4379",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ktJSDXDISKSyuXHb.jpg",
    title: "Morning Haze",
    category: "Landscape",
    season: "Autumn",
    mood: "Nostalgic",
    description: "A winding dirt road disappears into golden morning haze, the backlit atmosphere reducing distant hills to soft, layered silhouettes.",
    orientation: "landscape",
  },
  {
    id: "IMG_4297",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ZgzxovAkdATTJSPA.jpg",
    title: "Swans at the Tower",
    category: "Wildlife",
    season: "Autumn",
    mood: "Quiet",
    description: "A pair of white swans rest on a still pond before a weathered wooden hunting tower, the warm autumn foliage framing the scene in gold.",
    orientation: "portrait",
  },
  {
    id: "IMG_5918",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/EyicaeNlRnghJcbX.jpg",
    title: "The Fisherman's Walk",
    category: "Documentary",
    season: "Winter",
    mood: "Solitary",
    description: "A lone figure carrying a fishing rod walks across a vast snow-covered embankment, leaving a trail of footprints in the pristine white surface.",
    orientation: "portrait",
  },
  {
    id: "IMG_3633",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/xqQmuZekkfniLFjk.jpg",
    title: "Vineyard in Fog",
    category: "Landscape",
    season: "Autumn",
    mood: "Ethereal",
    description: "Rows of a vineyard converge toward a small farmhouse before disappearing into a wall of dense fog, the geometric precision of the rows dissolving into mystery.",
    orientation: "portrait",
  },
  {
    id: "IMG_5979",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/uJxvzbUaQIPVYJUx.jpg",
    title: "Crow in Winter",
    category: "Wildlife",
    season: "Winter",
    mood: "Melancholic",
    description: "A solitary crow perches on a snow-covered beam extending over a frozen river, the misty background reducing the world to a study in pale grey.",
    orientation: "landscape",
  },
  {
    id: "IMG_5876",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/xAfKzPjaznuUqZiN.jpg",
    title: "Blue Forest",
    category: "Winter",
    season: "Winter",
    mood: "Magical",
    description: "A snow-laden forest glows in deep blue twilight, a hidden light source casting ethereal illumination through the laden branches.",
    orientation: "landscape",
  },
  {
    id: "IMG_4047",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ZnOMuIyDELUVavyv.jpg",
    title: "Low Water",
    category: "Documentary",
    season: "Autumn",
    mood: "Environmental",
    description: "Seen from above, two tiny figures explore the exposed sandbars of a low-water river, the organic shapes of sand and water creating an abstract landscape.",
    orientation: "landscape",
  },
  {
    id: "IMG_3573",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/TKBEKUzrJzAMbvgv.jpg",
    title: "Steel Bridge at Dusk",
    category: "Architecture",
    season: "Summer",
    mood: "Nostalgic",
    description: "The geometric steel arch of an old bridge frames a golden sunset, the structural elements casting long shadows across cobblestone.",
    orientation: "landscape",
  },
  {
    id: "IMG_5559",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/GodNxIchzTSJKLwQ.jpg",
    title: "Frozen Stream",
    category: "Winter",
    season: "Winter",
    mood: "Serene",
    description: "A frozen stream winds through a snow-covered landscape, the dark silhouettes of bare trees reflected in the ice-blue surface.",
    orientation: "landscape",
  },
  {
    id: "IMG_0554",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/cxBQadkptloTzoVI.jpg",
    title: "Cracked Earth",
    category: "Documentary",
    season: "Summer",
    mood: "Environmental",
    description: "A mother and child walk across a vast cracked lakebed, the geometric patterns of dried mud stretching to the horizon under a bright summer sky.",
    orientation: "landscape",
  },
  {
    id: "IMG_3127",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/WqiRIqUMcXcfzMTV.jpg",
    title: "River Swing",
    category: "Documentary",
    season: "Summer",
    mood: "Playful",
    description: "A young man swings from a tree branch over a river as a companion watches from a boat below, the scene captured through atmospheric summer haze.",
    orientation: "portrait",
  },
  {
    id: "IMG_3071",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/qPkfyaAXGuFEqHuV.jpg",
    title: "Riverside Layers",
    category: "Architecture",
    season: "Summer",
    mood: "Observational",
    description: "A cyclist on an embankment above a houseboat creates a study in horizontal layers — road, water, boat, and sky stacked in precise bands.",
    orientation: "portrait",
  },
  {
    id: "IMG_4032",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/FWKhXrphUMSWTlEf.jpg",
    title: "Empty Bench",
    category: "Documentary",
    season: "Autumn",
    mood: "Contemplative",
    description: "A lone park bench sits on a sandy riverbank, its solitude amplified by the vast open water and the diagonal line of the shore.",
    orientation: "landscape",
  },
  {
    id: "IMG_2954",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/UnAhSjuOOSAyhMYx.jpg",
    title: "Heron on Ruins",
    category: "Wildlife",
    season: "Summer",
    mood: "Quiet",
    description: "A grey heron perches atop a weathered concrete pillar overgrown with yellow lichen, surveying the river from its elevated post.",
    orientation: "landscape",
  },
  {
    id: "IMG_4825",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MYxbPDJnqfSePtqR.jpg",
    title: "Dog on the Path",
    category: "Documentary",
    season: "Autumn",
    mood: "Intimate",
    description: "A small dog trots toward the camera along a leaf-strewn forest path, the bokeh-softened trees creating a warm, intimate atmosphere.",
    orientation: "portrait",
  },
  {
    id: "IMG_5070_DxO",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/JRaAEmHGIyLEHtqH.jpg",
    title: "Autumn Portrait",
    category: "Documentary",
    season: "Autumn",
    mood: "Warm",
    description: "A contemplative portrait set against the rich textures of autumn, the warm tones of the season enveloping the subject in natural light.",
    orientation: "portrait",
  },
];

export const categories = ["All", "Landscape", "Wildlife", "Documentary", "Winter", "Architecture"];

export const featuredPhotos = photos.filter(p => p.featured);
