// Design: "Fog & Field" Nordic Atmospheric Minimalism
// Complete portfolio by Goran Vucicevic

export interface Photo {
  id: string;
  src: string;
  title: string;
  category: string;
  season: string;
  mood: string;
  description: string;
  orientation: "landscape" | "portrait" | "square";
  featured?: boolean;
  story?: string;
}

export const photos: Photo[] = [
  // ─── ORIGINAL 25 PHOTOS ───────────────────────────────────────────────────
  {
    id: "IMG_7274",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/HDtgZzlpKeEnnixw.jpg",
    title: "Samoća na mirnoj vodi",
    category: "Divlja priroda",
    season: "Zima",
    mood: "Minimalistično",
    description: "Usamljena bela ptica klizi po jezeru obavijenom maglom, okružena sablasnim siluetama potopljenih stabala koja se ogledaju u staklastoj površini.",
    orientation: "landscape",
    featured: true,
    story: `## Tišina koja govori

Bilo je jedno od onih zimskih jutara kada se svet zaustavi. **Magla je obavijala jezero** kao pamučni prekrivač, gutajući zvuke i boje, ostavljajući samo belo i sivo.

Čekao sam skoro sat vremena, nepomičan na obali, dok se temperatura spuštala ispod nule. Prsti su mi utrnuli oko okidača.

### Savršen trenutak

A onda se pojavila — *usamljena bela čaplja*, klizeći po površini vode bez ijednog talasa. Njen odraz je bio savršen na staklastoj površini. Potopljena stabla iza nje stvorila su sablasni okvir, kao da je cela scena izrežirana za pozorišnu predstavu.

> Ponekad najlepše fotografije nastaju kada prestaneš da tražiš i počneš da čekaš.

Ovo je jedna od mojih najdražih slika jer govori o **strpljenju** — i u fotografiji i u životu. Svaki put kad je pogledam, setim se tog ledenog jutra i tople zahvalnosti što sam bio tamo u pravom trenutku.`,
  },
  {
    id: "IMG_9755",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/VCnGIYkysqDItZzP.jpg",
    title: "Beskrajni horizont",
    category: "Pejzaž",
    season: "Leto",
    mood: "Epično",
    description: "Usamljeni planinar stoji na ivici planinskog vrha, zasenjen panoramskim pogledom na valovita brda i dramatično nebo ispunjeno oblacima.",
    orientation: "landscape",
    featured: true,
    story: `## Između neba i zemlje

Posle pet sati uspona, stajao sam na ivici sveta. **Valovita brda** su se prostirala u svim pravcima, svako sledeće bleđe od prethodnog, dok se nebo mešalo sa horizontom u beskrajnoj plavoj izmaglici.

Planinar ispred mene je zastao na samom rubu — mala silueta naspram ogromnog prostranstva. Nije se pomerao minutima, samo je gledao.

### Razmera

Ova slika me podseća koliko smo *mali* u poređenju sa prirodom. Ali paradoksalno — upravo ta malenkost nas čini hrabrim. Svaki korak na planini je pobeda nad gravitacijom, nad strahom, nad sopstvenim granicama.

- **Nadmorska visina**: ~1.700m
- **Vreme uspona**: 5 sati
- **Temperatura**: 14°C sa vetrom

> Na vrhu planine shvatiš da cilj nikada nije bio vrh — cilj je bio put.`,
  },
  {
    id: "IMG_3240",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/QQVxcHcaHkvwMgzX.jpg",
    title: "Zlatna reka",
    category: "Pejzaž",
    season: "Leto",
    mood: "Toplo",
    description: "Silueta ribara seče sjajni zalazak sunca na reci, dok se voda pretvara u tečno zlato pod umirućim svetlom.",
    orientation: "landscape",
    featured: true,
    story: `## Zlatni sat

Ribari na ovoj reci znaju nešto što većina nas zaboravlja — da je **zalazak sunca** najdragoceniji deo dana. Svako veče, kada se sunce spusti dovoljno nisko, reka se pretvori u tečno zlato.

Stigao sam na obalu oko 18:30, noseći samo fotoaparat i stativ. Svetlost se menjala svakog minuta — od žute, preko narandžaste, do duboke crvene.

### Tehnika

Ovo je snimljeno sa **teleobiektivom od 200mm**, što je kompresovalo slojeve — ribara, vodu i nebo — u jedan ravni, grafički kompozit. Ekspozicija je bila namerno podeksponirana za pola stopa da bi se sačuvala zasićenost boja.

1. Čekanje pravog trenutka (oko 40 minuta)
2. Fokus na siluetu ribara
3. Ekspozicija za nebo, ne za senke

> Najbolje svetlo traje samo **12 minuta**. Profesionalci to zovu "zlatni prozor" — i kad prođe, prošao je zauvek.`,
  },
  {
    id: "IMG_9496",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/EOBzrDyWgvGVVlSe.jpg",
    title: "Mraz u sumrak",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Dramatično",
    description: "Livada pokrivena mrazom sjaji jantarno ispod olujnog neba, dok napetost između tople zemlje i hladnog neba stvara nadzemaljsku atmosferu.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_2084",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/nZlZeAsmfYtyHeUA.jpg",
    title: "U magli",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Tajanstveno",
    description: "Dvoje planinara hodaju ruku pod ruku u šumu bukve ispunjenu maglom, njihove male figure gutaju katedralne krošnje.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_3176",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/FvNzOxSctVrFGChf.jpg",
    title: "Čaplja u letu",
    category: "Divlja priroda",
    season: "Leto",
    mood: "Graciozno",
    description: "Siva čaplja klizi nisko nad rekom u maglovitom jutru, njena krila hvataju pozadinsko svetlo ranog sunca koje se filtrira kroz priobalne vrbe.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_5504",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/SJFJreCoxkjEXwHk.jpg",
    title: "Svetiljke u snegu",
    category: "Zima",
    season: "Zima",
    mood: "Romantično",
    description: "Tri vintage ulične svetiljke sijaju toplim jantarnim svetlom na pozadini dubokog plavog zimskog sumraka, njihove baze zakopane u dubokom snegu.",
    orientation: "landscape",
  },
  {
    id: "IMG_6088",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ZWhRjLCLNSBKZlyT.jpg",
    title: "Planinska zima",
    category: "Pejzaž",
    season: "Zima",
    mood: "Veličanstveno",
    description: "Mala kuća smestila se u dolini prekrivenoj snegom, dok se pošumljeni grebeni gube u plavoj atmosferskoj izmaglici u sve daljim slojevima.",
    orientation: "portrait",
  },
  {
    id: "IMG_1797",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/WGoXASgTGtzKcmca.jpg",
    title: "Oluja nad njivama",
    category: "Pejzaž",
    season: "Leto",
    mood: "Dramatično",
    description: "Usamljeno drvo stoji kao stražar na horizontu geometrijskih njiva dok se dramatično olujno nebo gradi iznad.",
    orientation: "portrait",
  },
  {
    id: "IMG_4379",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/LpwXrGXCNzuiGZDh.jpg",
    title: "Jutarnja izmaglica",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Nostalgično",
    description: "Vijugavi zemljani put nestaje u zlatnoj jutarnjoj izmaglici, dok pozadinsko osvetljenje svodi udaljene brežuljke na meke, slojevite siluete.",
    orientation: "landscape",
  },
  {
    id: "IMG_4297",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/CHxgZDOikfntmEiu.jpg",
    title: "Labudovi kod tornja",
    category: "Divlja priroda",
    season: "Jesen",
    mood: "Mirno",
    description: "Par belih labudova odmara na mirnom ribnjaku ispred trošne drvene lovačke čeke, dok toplo jesensko lišće uokviruje scenu u zlatu.",
    orientation: "portrait",
  },
  {
    id: "IMG_5918",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/IOrsqdiFRQBIDckM.jpg",
    title: "Ribarev put",
    category: "Dokumentarno",
    season: "Zima",
    mood: "Usamljeno",
    description: "Usamljena figura sa štapom za pecanje hoda po ogromnom snežnom nasipu, ostavljajući trag stopala u neokrnjenoj beloj površini.",
    orientation: "portrait",
  },
  {
    id: "IMG_3633",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/atMqrMIeyDpCxUJY.jpg",
    title: "Vinograd u magli",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Eterično",
    description: "Redovi vinograda konvergiraju ka maloj farmi pre nego što nestanu u gustoj magli, geometrijska preciznost redova rastvara se u misteriji.",
    orientation: "portrait",
  },
  {
    id: "IMG_5979",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/YMfmxwWAoErnoZQc.jpg",
    title: "Vrana u zimi",
    category: "Divlja priroda",
    season: "Zima",
    mood: "Melanholično",
    description: "Usamljena vrana sedi na gredi prekrivenoj snegom koja se pruža nad zaleđenom rekom, maglovita pozadina svodi svet na studiju u bledom sivom.",
    orientation: "landscape",
  },
  {
    id: "IMG_5876",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/FfVqXHmoLQwaXmUR.jpg",
    title: "Plava šuma",
    category: "Zima",
    season: "Zima",
    mood: "Čarobno",
    description: "Šuma opterećena snegom sija u dubokom plavom sumraku, skriveni izvor svetlosti baca eterično osvetljenje kroz snegom natovljene grane.",
    orientation: "landscape",
  },
  {
    id: "IMG_4047",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/tZipeOxSOOFsgXbT.jpg",
    title: "Mala voda",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Ekološki",
    description: "Gledano odozgo, dve sitne figure istražuju otkrivene sprudove reke sa niskim vodostanjem, organski oblici peska i vode stvaraju apstraktni pejzaž.",
    orientation: "landscape",
  },
  {
    id: "IMG_3573",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/tisuVxvNDCzSygEH.jpg",
    title: "Čelični most u sumrak",
    category: "Arhitektura",
    season: "Leto",
    mood: "Nostalgično",
    description: "Geometrijski čelični luk starog mosta uokviruje zlatni zalazak sunca, strukturni elementi bacaju duge senke po kaldrmi.",
    orientation: "landscape",
  },
  {
    id: "IMG_5559",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/LlIdCbiYovVQHnhM.jpg",
    title: "Zaleđeni potok",
    category: "Zima",
    season: "Zima",
    mood: "Spokojno",
    description: "Zaleđeni potok vijuga kroz pejzaž prekriven snegom, tamne siluete golih stabala ogledaju se u ledeno plavoj površini.",
    orientation: "landscape",
  },
  {
    id: "IMG_0554",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/dkLjuAbrAmSgGqLi.jpg",
    title: "Ispucala zemlja",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Ekološki",
    description: "Majka i dete hodaju po ogromnom ispucalom dnu jezera, geometrijski uzorci suve blate protežu se do horizonta pod jarkim letnjim nebom.",
    orientation: "landscape",
  },
  {
    id: "IMG_3127",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/SiTvQboHDFIsWuyc.jpg",
    title: "Ljuljanje nad rekom",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Veselo",
    description: "Mlad čovek se ljulja sa grane drveta nad rekom dok drug posmatra iz čamca ispod, scena uhvaćena kroz atmosfersku letnju izmaglicu.",
    orientation: "portrait",
  },
  {
    id: "IMG_3071",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ARGJUjbdEZkWRcth.jpg",
    title: "Slojevi uz reku",
    category: "Arhitektura",
    season: "Leto",
    mood: "Posmatrački",
    description: "Biciklista na nasipu iznad kućnog broda stvara studiju horizontalnih slojeva — put, voda, brod i nebo složeni u precizne pojaseve.",
    orientation: "portrait",
  },
  {
    id: "IMG_4032",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/TyvNBAKdpmvGyfRO.jpg",
    title: "Prazna klupa",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Kontemplativno",
    description: "Usamljena klupa stoji na peščanoj obali reke, njena samoća pojačana ogromnom otvorenom vodom i dijagonalnom linijom obale.",
    orientation: "landscape",
  },
  {
    id: "IMG_2954",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/SXEHacnSFkgqKJxj.jpg",
    title: "Čaplja na ruševinama",
    category: "Divlja priroda",
    season: "Leto",
    mood: "Mirno",
    description: "Siva čaplja sedi na vrhu trošnog betonskog stuba obraslim žutim lišajem, nadgledajući reku sa svog uzvišenog mesta.",
    orientation: "landscape",
  },
  {
    id: "IMG_4825",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/yPZiVjBRqnJkYzGK.jpg",
    title: "Pas na stazi",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Intimno",
    description: "Mali pas trči prema kameri duž šumske staze posute lišćem, bokeh-omekšana stabla stvaraju toplu, intimnu atmosferu.",
    orientation: "portrait",
  },
  // ─── NEW 65 PHOTOS ────────────────────────────────────────────────────────
  {
    id: "IMG_4328",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/rolthEeVfOjGOmaS.jpg",
    title: "Poletanje labuda",
    category: "Divlja priroda",
    season: "Jesen",
    mood: "Dramatično",
    description: "Labud uzleće sa površine vode uz dramatičan prskanje, bela silueta ptice oštra na tamnoj pozadini šume. Savršen tajming uhvatio je trenutak između mira i pokreta.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_4468",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/tlfoYMkmOHnHpkUX.jpg",
    title: "Labud u jutarnjoj magli",
    category: "Divlja priroda",
    season: "Jesen",
    mood: "Eterično",
    description: "Usamljeni labud plovi mirnom rekom u zlatnoj jutarnjoj magli, nadvišen siluetom drveta koje se nadvija nad vodom. Slika dočarava savršenu tišinu ranog jutra.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_3385",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/CPjCDeSfwIVIVHnM.jpg",
    title: "Polja u izmaglici",
    category: "Pejzaž",
    season: "Leto",
    mood: "Apstraktno",
    description: "Pogled odozgo na pruge oranica i useva koje se pretvaraju u horizontalne trake boje — okera, sijena i zelene — u toploj letnjem izmaglici. Pejzaž postaje grafička apstrakcija.",
    orientation: "landscape",
  },
  {
    id: "IMG_4420",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MawjpmaEYLAambzO.jpg",
    title: "Ribar u zlatnom jutru",
    category: "Dokumentarno",
    season: "Proleće",
    mood: "Poetično",
    description: "Ribar sedi na palom stablu nad rekom dok zlatna jutarnja svetlost probija kroz maglom ispunjenu šumu iza njega. Slojevi svetlosti, magle i vegetacije stvaraju gotovo slikarsku kompoziciju.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_4476",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/wiwhSOLURCJaaKik.jpg",
    title: "Drveće u magli",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Tajanstveno",
    description: "Stabla duž šumske staze nestaju u gustoj jutarnjoj magli, toplo-hladni kontrast boja stvara atmosferu između sna i jave.",
    orientation: "portrait",
  },
  {
    id: "IMG_8511",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/riSyreNjMoMHUkrT.jpg",
    title: "Labudovi na snegu",
    category: "Divlja priroda",
    season: "Zima",
    mood: "Grafički",
    description: "Labudovi na snežnoj obali reke, poplavljene topole odražavaju se u vodi. Vertikalne linije stabala i njihovih odraza stvaraju ritmičan grafički uzorak.",
    orientation: "landscape",
  },
  {
    id: "IMG_4469",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/JEMtcQpLphNXdmFU.jpg",
    title: "Plovci u magli",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Minimalistično",
    description: "Ribolovni plovci lebde na sivoplavoj vodi prekrivenoj maglom — narandžaste i crvene tačke jedine su boje u monohromnom pejzažu. Jedna od najoriginalnijih apstrakcija u celom portfoliju.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_5057",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/cZSdvEKnezuuUtTN.jpg",
    title: "Pogled na grad",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Kontemplativno",
    description: "Par sedi na padini brda i posmatra gradsku panoramu u zlatnom sumraku. Intimni trenutak dvoje ljudi naspram ogromnog urbanog pejzaža.",
    orientation: "landscape",
  },
  {
    id: "IMG_9934",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/hNKSyIAbRClnPOUa.jpg",
    title: "Kuća pred oluju",
    category: "Arhitektura",
    season: "Leto",
    mood: "Dramatično",
    description: "Stara seoska kuća sa crvenim krovom okružena zelenim njivama pod dramatičnim olujnim nebom. Kontrast između tople arhitekture i tamnog neba stvara snažnu napetost.",
    orientation: "landscape",
  },
  {
    id: "IMG_0849",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/mHnljIgsvEDDDcTD.jpg",
    title: "Samoća u sumrak",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Melanholično",
    description: "Silueta usamljene osobe na klupi okružena uličnim lampama na pozadini spektakularnog narandžastog zalaska sunca. Jedna od najsnažnijih emocionalnih slika u portfoliju.",
    orientation: "landscape",
    featured: true,
    story: `## Priča o čekanju

Svako veče, otprilike u isto vreme, ovaj čovek je dolazio na istu klupu. **Sedeo je sam**, okrenut prema zapadu, i gledao kako sunce tone.

Nisam ga poznavao. Nisam ga ni pitao zašto dolazi. Fotografisao sam ga tri večeri za redom, iz daljine, ne želeći da narusim njegov mir.

### Treće veče

Trećeg večera nebo je *eksplodiralo* bojama — narandžastom, zlatnom, ružičastom. Ulične lampe su se upalile jedna za drugom, okružujući ga toplim krugovima svetlosti. Njegova silueta je izgledala kao da pripada nekom drugom vremenu.

> Ova fotografija me uvek podseća na reči Edvarda Hopera: *"Možda nisam baš ljudski. Ono što sam želeo da uradim je da naslikam sunčevu svetlost na zidu kuće."*

Ponekad jedna slika kaže sve o **samoći** — ne onoj tužnoj, već onoj izabranoj. Onoj koja nas vraća sebi.`,
  },
  {
    id: "IMG_6285",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/YiuonxUxWjOGAhmv.jpg",
    title: "Dim nad ravnicom",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Grafički",
    description: "Kolona dima uzdiže se dijagonalno iznad ravnog horizonta pod jarkim plavim nebom. Minimalistična kompozicija svodi pejzaž na esenciju — zemlja, nebo i trag čoveka.",
    orientation: "landscape",
  },
  {
    id: "IMG_5505",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MzYrcjkNFtbRHNrh.jpg",
    title: "Letnji dan na reci",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Nostalgično",
    description: "Stara automobilska guma vezana za drvo kao ljuljaška visi nad rekom u zlatnom svetlu zalaska sunca. Prizor odišu toplinom srpskog leta i jednostavnim radostima.",
    orientation: "landscape",
  },
  {
    id: "IMG_8498",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/qvSibUGWBifCoHnY.jpg",
    title: "Roda na ledu",
    category: "Divlja priroda",
    season: "Zima",
    mood: "Elegantno",
    description: "Bela roda gazi po zaleđenoj vodi pored male ptice barke, desaturisana zimska paleta ističe crvene noge rode kao jedini akcenat boje.",
    orientation: "landscape",
  },
  {
    id: "IMG_0776",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/izlCIlEgGKXoYqdJ.jpg",
    title: "Planinski horizont",
    category: "Pejzaž",
    season: "Leto",
    mood: "Veličanstveno",
    description: "Panorama planinskog masiva sa slojevitim grebenima koji nestaju u olujnim oblacima, četinarska šuma u prvom planu daje dubinu i razmeru.",
    orientation: "landscape",
  },
  {
    id: "IMG_5395",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/UwGRqpqLbqiUFcIJ.jpg",
    title: "Put kroz ravnicu",
    category: "Pejzaž",
    season: "Leto",
    mood: "Slobodno",
    description: "Prašnjavi put vijuga kroz bujnu ravnicu pod dramatičnim letnjem nebom, usamljeno topola stoji kao orijentir u beskrajnom prostoru.",
    orientation: "landscape",
  },
  {
    id: "IMG_4053",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/OWMuVCxHRiRSQJhJ.jpg",
    title: "Podolci na paši",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Etnografski",
    description: "Beli podolski goveda pasu pored tradicionalnog garma na ravnici. Slika dokumentuje nestajuće elemente srpskog seoskog nasleđa.",
    orientation: "landscape",
  },
  {
    id: "IMG_2569",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/qjUyxZUiuyXCYvuk.jpg",
    title: "Garan pred oluju",
    category: "Arhitektura",
    season: "Leto",
    mood: "Dramatično",
    description: "Tradicionalni drveni garan — simbol panonskog pejzaža — siluetiran na pozadini dramatičnog olujnog neba. Ikona srpske ravnice u svom najmoćnijem obliku.",
    orientation: "portrait",
    featured: true,
    story: `## Poslednji stražar ravnice

**Garani** nestaju. Svake godine ih je sve manje — propadaju, raspadaju se, ili ih jednostavno sruše da bi napravili mesta za nešto "korisnije". A oni su nekada bili *srce svakog panonskog sela*.

Ovaj garan sam pronašao na putu između dva sela, sam na njivi, okružen pšenicom. Iza njega se skupljala oluja — teški, tamni oblaci koji su se kretali iznenađujucom brzinom.

### Simbolika

Garan je nekada služio za navodnjavanje — drvena poluga sa kantom na jednom kraju i protivteg na drugom. Jednostavan mehanizam, star stotinama godina. Ali njegova **silueta** je nešto posebno — vitka, elegantna, gotovo kaligrafska linija na horizontu.

- **Lokacija**: Sremska ravnica, okolina Rume
- **Doba dana**: Kasno popodne, pred oluju
- **Preostali garani u Sremu**: manje od 50

> Fotografišem ove strukture jer znam da za deset godina možda neće postojati. Svaka slika je mali čin očuvanja.`,
  },
  {
    id: "IMG_8606",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/zmJDlLeZGyQtjhMS.jpg",
    title: "Dva drveta",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Minimalistično",
    description: "Dve usamljene topole stoje na uzbrazdanoj njivi pod sivim nebom. Savršena minimalistička kompozicija — samo zemlja, nebo i dva svedoka prolaznosti.",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "IMG_5044",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ktTBQqyfhpOHTQgb.jpg",
    title: "Stara kapija",
    category: "Arhitektura",
    season: "Jesen",
    mood: "Nostalgično",
    description: "Stara drvena kapija obrasla bršljanom, žuta ljuspava boja zida i jesenji listovi stvaraju bogatu teksturu propadanja i lepote.",
    orientation: "portrait",
  },
  {
    id: "IMG_0841",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/oeIZXLGNGRzIhtWe.jpg",
    title: "Dvoje u sumrak",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Poetično",
    description: "Siluete dvoje starijih — muškarca i žene — na klupi pored ulične lampe dok olujno nebo plamti u narandžastom i zlatnom. Slika govori o ljubavi, starosti i prolaznosti.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_8135",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/vwfPQRvthgbrEBKb.jpg",
    title: "Zimski mir",
    category: "Pejzaž",
    season: "Zima",
    mood: "Spokojno",
    description: "Planinska scena sa cedrom pod snegom, drvenom ogradom i krovom planinarske kuće u kristalno čistom zimskom svetlu. Visoki ključ, čistoća, tišina.",
    orientation: "landscape",
  },
  {
    id: "IMG_5354",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ISoRzNrBYrabWGsF.jpg",
    title: "Stara tvrđava",
    category: "Arhitektura",
    season: "Jesen",
    mood: "Istorijsko",
    description: "Kula srednjovekovne tvrđave na jesenjem brežuljku, zlatno svetlo na kamenim zidovima i šareno lišće stvaraju bogatu, slojevitu scenu.",
    orientation: "portrait",
  },
  {
    id: "IMG_6694",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ihUSaVHXwduyBNSL.jpg",
    title: "Sasak u cvatu",
    category: "Divlja priroda",
    season: "Proleće",
    mood: "Delikatno",
    description: "Makro fotografija cveta saska — ljubičaste latice i žuti prašnici na pozadini suve trave. Krupni plan otkriva lepotu koja se lako previđa.",
    orientation: "portrait",
  },
  {
    id: "IMG_0278",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/eyoVjrqcEcdKlbPH.jpg",
    title: "Vinogradi i ravnica",
    category: "Pejzaž",
    season: "Leto",
    mood: "Mirno",
    description: "Pogled odozgo na vinogradske terase i panonsku ravnicu u zlatnom svetlu, meka teal-zlatna paleta i savršeni mir kasnog popodneva.",
    orientation: "landscape",
  },
  {
    id: "IMG_9511",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/BYVeZSoJkdGGJvZV.jpg",
    title: "Polje repice",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Živahno",
    description: "Žuto polje repice u punom cvatu na pozadini dubokog plavog neba i uzoraka oranica. Snažan kontrast boja slavi dolazak proleća.",
    orientation: "landscape",
  },
  {
    id: "IMG_4547",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ZQFMaZeftnGDDgTB.jpg",
    title: "Fruška Gora pred oluju",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Dramatično",
    description: "Pogled na Frušku Goru sa TV tornjem i belom vilom, crvena zemlja oranica u prvom planu i dramatično olujno nebo iznad.",
    orientation: "landscape",
  },
  {
    id: "IMG_3186",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/isvAXkMRfZCOcqfX.jpg",
    title: "Zimska bara",
    category: "Pejzaž",
    season: "Zima",
    mood: "Melanholično",
    description: "Zimska panorama bare sa golim topolama, trstičištem i zaleđenom vodom u daljini — labudovi kao bele tačke u sivom pejzažu. Savršeno horizontalno slojevanje.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_2736",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/cDRQscHDFyHapfFM.jpg",
    title: "Sremski pejzaž",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Posmatrački",
    description: "Panorama sremskih sela i industrijskih dimnjaka snimljena sa uzvisine, dokumentujući napetost između prirodnog pejzaža i industrijskog nasleđa.",
    orientation: "landscape",
  },
  {
    id: "IMG_0479",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/CGMVoOJYQUAprbJH.jpg",
    title: "Jezero u kamenolomu",
    category: "Pejzaž",
    season: "Leto",
    mood: "Neobično",
    description: "Napušteni površinski kop pretvoren u tirkizno jezero pod dramatičnim nebom. Priroda preuzima industrijsku ranu — neobična lepota transformacije.",
    orientation: "landscape",
  },
  {
    id: "IMG_2475",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/fzviaCyKLiAcLUXr.jpg",
    title: "Meteora",
    category: "Arhitektura",
    season: "Leto",
    mood: "Veličanstveno",
    description: "Manastiri Meteore na stenskim stubovima iznad doline, slojevita atmosfera i dramatična svetlost. Jedno od najimpresivnijih mesta na svetu.",
    orientation: "landscape",
  },
  {
    id: "IMG_7386",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/uvpnpCTkttykdUyf.jpg",
    title: "Poplavna ravnica",
    category: "Pejzaž",
    season: "Leto",
    mood: "Dramatično",
    description: "Poplavljena Sava ili Dunav sa potopljenim žbunjem i dramatičnim kumulusnim oblacima, živopisna plavo-zelena paleta.",
    orientation: "landscape",
  },
  {
    id: "IMG_4129",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ijRESkVAINZYGvwe.jpg",
    title: "Paviljon na Paliću",
    category: "Arhitektura",
    season: "Jesen",
    mood: "Elegantno",
    description: "Austrougarski paviljon na obali Palićkog jezera okružen jesenskim drvećem, teleobiektiv komprimuje prostor u elegantnu arhitektonsku studiju.",
    orientation: "landscape",
  },
  {
    id: "IMG_0823",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/mZbEAcIoQzlqCZYp.jpg",
    title: "Zlatno jutro na reci",
    category: "Pejzaž",
    season: "Leto",
    mood: "Veličanstveno",
    description: "Dunav ili Sava u zlatnom jutarnjom svetlu, poplava topola u prvom planu i Fruška Gora u pozadini. Jedna od najlepših slika u celom portfoliju.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_5514",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/CAejADayogrZIVgH.jpg",
    title: "Most pred oluju",
    category: "Arhitektura",
    season: "Leto",
    mood: "Dramatično",
    description: "Stari lučni most sa narandžastom ogradom pod dramatičnim olujnim nebom, snažna grafička kompozicija arhitekture i atmosfere.",
    orientation: "landscape",
  },
  {
    id: "IMG_3994",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/RhQzwXYqkiuzWvSL.jpg",
    title: "Put ka zalasku",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Poetično",
    description: "Prašnjavi put vodi prema narandžasto-ružičastom zalasku sunca nad dolinom, vertikalni format naglašava put kao metaforu putovanja.",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "IMG_6819",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/yPKdBfelCDlQJaNa.jpg",
    title: "Ravnica pred oluju",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Dramatično",
    description: "Vertikalna kompozicija panonske ravnice sa prugama njiva i žutom repicm u dnu, nebo zauzima dve trećine kadra u svom olujnom veličanstvu.",
    orientation: "portrait",
  },
  {
    id: "IMG_2503",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/QrZiJTdPgBRzzYTU.jpg",
    title: "Na vrhu sveta",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Radosno",
    description: "Dete stoji na stenama Meteore dok se dolina prostire ispod, panoramski pogled i sloboda dečijeg istraživanja u jednoj slici.",
    orientation: "landscape",
  },
  {
    id: "IMG_0551",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MNMmPjTLqsalhmTb.jpg",
    title: "Isušeno jezero",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Ekološki",
    description: "Dete hoda po ispucalom dnu isušenog jezera, geometrijski uzorci suve blate protežu se do horizonta. Snažna ekološka poruka u jednoj slici.",
    orientation: "portrait",
  },
  {
    id: "IMG_0140",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/hnLBuIhqTDRFOOSU.jpg",
    title: "Zalazak na reci",
    category: "Pejzaž",
    season: "Leto",
    mood: "Toplo",
    description: "Reka u zlatnom zalasku sunca sa privezanim čamcima i drvoredom na obali, gotovo slikarska kvaliteta svetlosti i boje.",
    orientation: "landscape",
  },
  {
    id: "IMG_3867",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/virlonVCpuQYXSRw.jpg",
    title: "Sunce kroz šumu",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Magično",
    description: "Dramatični krepuskularni zraci probijaju se kroz jesensku šumu, zlatno svetlo između stabala stvara gotovo nadrealan prizor.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_5642",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/eneoFEiiRhCYgUpG.jpg",
    title: "Jesenja Fruška Gora",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Veličanstveno",
    description: "Panorama Fruške Gore u punoj jesennjoj raskoši, slojeviti brežuljci sa šarenim lišćem i oblačno nebo stvaraju bogatu, slojevitu scenu.",
    orientation: "landscape",
  },
  {
    id: "IMG_8603",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/OXqxCrhazwiSLMjS.jpg",
    title: "Dva drveta na njivi",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Minimalistično",
    description: "Dve usamljene topole na oranici — jedna zelena, jedna žuta — na pozadini sivog neba. Savršena minimalistička studija usamljenosti i kontrasta.",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "IMG_3196",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/UbbyUEmhKonNhWmM.jpg",
    title: "Vijugavi put",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Grafički",
    description: "Vijugavi prašnjavi put kroz sremske oranice, teleobiektiv komprimuje prostor u apstraktni uzorak tekstura i boja ranog proleća.",
    orientation: "landscape",
  },
  {
    id: "IMG_5374",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/bGVInojYozwVoJmp.jpg",
    title: "Proleće na njivama",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Svežina",
    description: "Valovite oranice pod oblacima koji bacaju senke, bogati tonovi crvene i okerne zemlje u kontrastu sa svetlim prugama neba.",
    orientation: "landscape",
  },
  {
    id: "IMG_5579",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/QrLgrQGFritMskNf.jpg",
    title: "Zmaj nad Sremom",
    category: "Dokumentarno",
    season: "Proleće",
    mood: "Radosno",
    description: "Porodica pušta zmaja na vrhu Fruške Gore dok se sremska ravnica prostire ispod. Jedna od najtoplijih i najemotivnijih slika u portfoliju.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_5954",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/hIOMrqLYRkNKcYqG.jpg",
    title: "Reka pred oluju",
    category: "Pejzaž",
    season: "Leto",
    mood: "Dramatično",
    description: "Reka sa privezanim čamcima pod olujnim nebom koje se ogleda u vodi, živopisne boje i dramatična atmosfera.",
    orientation: "landscape",
  },
  {
    id: "IMG_4965",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/oUBsqNYwyHQgObpq.jpg",
    title: "Šumska magla",
    category: "Pejzaž",
    season: "Leto",
    mood: "Tajanstveno",
    description: "Bukova šuma Fruške Gore u plavičastoj magli sumraka, vertikalna stabla nestaju u difuznoj svetlosti. Jedna od najatnmosferičnijih šumskih slika.",
    orientation: "portrait",
  },
  {
    id: "IMG_2810",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/PQONMohlSNixmCGa.jpg",
    title: "Zimska šuma",
    category: "Pejzaž",
    season: "Zima",
    mood: "Apstraktno",
    description: "Ekstremna teleobiektiv kompresija zimske šume — bele breze na tamnoj pozadini četinara. Gotovo akvarelna, slikarska kvaliteta.",
    orientation: "landscape",
  },
  {
    id: "IMG_8223",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/gBiekjQxweHktGzq.jpg",
    title: "Jesenja padina",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Mirno",
    description: "Jesennja padina sa slojevima vegetacije — zeleni borovi, gola lišćarska stabla i zlatna livada — u mekoj difuznoj svetlosti.",
    orientation: "landscape",
  },
  {
    id: "IMG_6350",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/DOynBnJWwONKgXfM.jpg",
    title: "Odmor pod bukvom",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Zajedništvo",
    description: "Grupa planinara odmara u podnožju ogromne stare bukve, kontrast između krhkih ljudskih figura i vekovnog stabla govori o razmeri i prolaznosti.",
    orientation: "landscape",
  },
  {
    id: "IMG_2482",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/IEhHzzdHgwgGtXke.jpg",
    title: "Meteora — manastir na steni",
    category: "Arhitektura",
    season: "Leto",
    mood: "Veličanstveno",
    description: "Teleobiektiv kadar manastira na stenskom stubu Meteore sa slojevitim planinama u pozadini. Jedna od tehnički najzahtevnijih i najuspelijih putnih fotografija.",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "IMG_9287",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/imtmUwDoedQPiryn.jpg",
    title: "Ruina crkve",
    category: "Arhitektura",
    season: "Zima",
    mood: "Duhovno",
    description: "Ruina srednjovekovne crkve sa kamenim lukom i krstom, maglovita dolina u pozadini i dramatično pozadinsko osvetljenje. Jedna od apsolutno najboljih slika u portfoliju.",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "IMG_8576",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/bqaMidTwZylibhsE.jpg",
    title: "Šuma u jesen",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Melanholično",
    description: "Unutrašnjost bukove šume sa paprati, palim lišćem i lensflare-om kroz gola stabla. Tamna, atmosferična, na granici jeseni i zime.",
    orientation: "landscape",
  },
  {
    id: "IMG_3029",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/xYHvrnnEddFBzLjW.jpg",
    title: "Sunce u šumi",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Magično",
    description: "Krepuskularni zraci probijaju se kroz jesensku šumu iznad potočnog kanjona, zlatno svetlo između stabala i palih trupaca stvara gotovo mistični prizor.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_4875",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/vqgfdZRSDywbiafs.jpg",
    title: "Dečak i pas na Fruškoj Gori",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Toplo",
    description: "Dečak sa psom na vrhu Fruške Gore sa spektakularnom jesennjom panoramom doline ispod. Toplina porodičnog trenutka i veličina prirode u jednoj slici.",
    orientation: "portrait",
  },
  {
    id: "IMG_5198",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/vkzbutxTsFZvyVZR.jpg",
    title: "Jesenja paleta",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Živahno",
    description: "Teleobiektiv krupni plan jesennje šumske krošnje — eksplozija crvene, narandžaste, žute i zelene. Čista apstrakcija boje, bez neba ni tla.",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "IMG_2404",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/mdpaIuZCAmTaMhke.jpg",
    title: "Napušteni dvorac",
    category: "Arhitektura",
    season: "Leto",
    mood: "Nostalgično",
    description: "Napuštena austrougarska vlastelinska kuća sa ornamentalnim krovom i dimnjacima, okružena letnjem zelenilom. Važan dokument kulturnog nasleđa.",
    orientation: "landscape",
  },
  {
    id: "IMG_8912",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/eIcCvYtmuOamyAlP.jpg",
    title: "Žitno polje",
    category: "Pejzaž",
    season: "Leto",
    mood: "Minimalistično",
    description: "Savršena minimalistička studija panonske ravnice — zlatno žitno polje zauzima donju trećinu, duboko plavo nebo gornju, usamljeni žbun jedini je akcent.",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "IMG_8173",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/heLXenYjjpArlRB.jpg",
    title: "Zlatni zraci",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Magično",
    description: "Jesenja bukova šuma prožeta zlatnim krepuskularnim zracima, pod od palih listova i senke stabala stvaraju dramatičan uzorak svetlosti i tame.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_9000",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/HSacVpZljjPftHcn.jpg",
    title: "Suncokretovo polje",
    category: "Pejzaž",
    season: "Leto",
    mood: "Veličanstveno",
    description: "Beskonačno polje suncokreta u zalasku sunca sa siluetom Fruške Gore u pozadini, cela scena kupana u zlatnoj izmaglici. Ikona srpskog leta.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_4405",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/WanBJGKIfonaHtiY.jpg",
    title: "Zlatni sat na reci",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Veličanstveno",
    description: "Kajakaši i ribar na reci u zlatnom satu, cela površina vode pretvara se u tečno zlato. Jedna od tehnički i estetski najuspelijih slika u portfoliju.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_1155",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/QpXyhAVSoVKRHXpI.jpg",
    title: "Divlji konji",
    category: "Divlja priroda",
    season: "Leto",
    mood: "Slobodno",
    description: "Krdo divljih konja pase na panonskoj ravnici u toplom jantarnom svetlu, teleobiektiv kompresija daje sceni gotovo filmski kvalitet.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_1967",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/QoDbEEAQRsZqThGC.jpg",
    title: "Stara bukva",
    category: "Pejzaž",
    season: "Leto",
    mood: "Veličanstveno",
    description: "Drevna bukva sa ogromnim korenjem koje se pruža po šumskom tlu, bujno letnje zelenilo i osećaj vekovne starosti i snage.",
    orientation: "landscape",
  },
  {
    id: "IMG_3067",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/YSKGYdNfpajQUjEp.jpg",
    title: "Kamenolom",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Apstraktno",
    description: "Teleobiektiv apstrakcija površinskog kopa — slojevita zemlja u nijansama crvene, okerne i bele sa malim bagerom koji naglašava razmeru. Zemlja kao apstraktna slika.",
    orientation: "portrait",
  },
  {
    id: "IMG_7084",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/DfijirOvEAihNJwS.jpg",
    title: "Livada u cvetu",
    category: "Pejzaž",
    season: "Proleće",
    mood: "Radosno",
    description: "Fruška Gora livada u punom prolećnom cvatu sa ljubičastim grahoricama, zeleni brežuljci i plavo nebo slave dolazak proleća.",
    orientation: "landscape",
  },
  {
    id: "IMG_4526",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/kCHKCyhjqmkxIKtu.jpg",
    title: "Staro imanje",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Nostalgično",
    description: "Zlatni retriver stoji ispred stare drvene seoske kuće pod dramatičnim olujnim nebom. Toplina psa, propadanje kuće i dramatično nebo u savršenoj ravnoteži.",
    orientation: "landscape",
  },
  {
    id: "IMG_4292",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/FfkdUcTorkVFHlaN.jpg",
    title: "Labudovi na kanalu",
    category: "Divlja priroda",
    season: "Jesen",
    mood: "Elegantno",
    description: "Dva labuda plove kanalomokruženi jesennjim vrbama i srebrnolisnim stablima, duboko plavo nebo i topla paleta stvaraju elegantnu, slojevitu kompoziciju.",
    orientation: "portrait",
  },
];

export const categories = ["Sve", "Pejzaž", "Divlja priroda", "Dokumentarno", "Zima", "Arhitektura", "Proleće"];

export const featuredPhotos = photos.filter(p => p.featured);
