// Photography Portfolio — Photo Data (Serbian)
// Design: "Fog & Field" Nordic Atmospheric Minimalism
// All CDN URLs for the 25 uploaded photographs

export interface Photo {
  id: string;
  src: string;
  title: string;
  category: string;
  season: string;
  mood: string;
  description: string;
  orientation: "landscape" | "portrait" | "square";
  featured?: boolean;
}

export const photos: Photo[] = [
  {
    id: "IMG_7274",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/wVWzLtIZKirqXoGB.jpg",
    title: "Samoća na mirnoj vodi",
    category: "Divlja priroda",
    season: "Zima",
    mood: "Minimalistično",
    description: "Usamljena bela ptica klizi po jezeru obavijenom maglom, okružena sablasnim siluetama potopljenih stabala koja se ogledaju u staklastoj površini.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_9755",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/hCZltdzYEfqikrIS.jpg",
    title: "Beskrajni horizont",
    category: "Pejzaž",
    season: "Leto",
    mood: "Epično",
    description: "Usamljeni planinar stoji na ivici planinskog vrha, zasenjen panoramskim pogledom na valovita brda i dramatično nebo ispunjeno oblacima.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_3240",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/BvLyvcSFYBQBeiZD.jpg",
    title: "Zlatna reka",
    category: "Pejzaž",
    season: "Leto",
    mood: "Toplo",
    description: "Silueta ribara seče sjajni zalazak sunca na reci, dok se voda pretvara u tečno zlato pod umirućim svetlom.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_9496",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/sdIwYeqhVCbFUFRc.jpg",
    title: "Mraz u sumrak",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Dramatično",
    description: "Livada pokrivena mrazom sjaji jantarno ispod olujnog neba, dok napetost između tople zemlje i hladnog neba stvara nadzemaljsku atmosferu.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_2084",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MkurKGZvBuwnNNxh.jpg",
    title: "U magli",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Tajanstveno",
    description: "Dvoje planinara — odrasla osoba i dete — hodaju ruku pod ruku u šumu bukve ispunjenu maglom, njihove male figure gutaju katedralne krošnje.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_3176",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/PykovAntDmOnNFNj.jpg",
    title: "Čaplja u letu",
    category: "Divlja priroda",
    season: "Leto",
    mood: "Graciozno",
    description: "Siva čaplja klizi nisko nad rekom u maglovitom jutru, njena krila hvataju pozadinsko svetlo ranog sunca koje se filtrira kroz priobalne vrbe.",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "IMG_5504",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/uHEorESBJLGARURq.jpg",
    title: "Svetiljke u snegu",
    category: "Zima",
    season: "Zima",
    mood: "Romantično",
    description: "Tri vintage ulične svetiljke sijaju toplim jantarnim svetlom na pozadini dubokog plavog zimskog sumraka, njihove baze zakopane u dubokom snegu.",
    orientation: "landscape",
  },
  {
    id: "IMG_6088",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/gOVvcFsoGtDcPUgv.jpg",
    title: "Planinska zima",
    category: "Pejzaž",
    season: "Zima",
    mood: "Veličanstveno",
    description: "Mala kuća smestila se u dolini prekrivenoj snegom, dok se pošumljeni grebeni gube u plavoj atmosferskoj izmaglici u sve daljim slojevima.",
    orientation: "portrait",
  },
  {
    id: "IMG_1797",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MmanKLaaJIZuabBQ.jpg",
    title: "Oluja nad njivama",
    category: "Pejzaž",
    season: "Leto",
    mood: "Dramatično",
    description: "Usamljeno drvo stoji kao stražar na horizontu geometrijskih njiva dok se dramatično olujno nebo gradi iznad, grafički uzorci useva stvaraju upečatljiv prvi plan.",
    orientation: "portrait",
  },
  {
    id: "IMG_4379",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ktJSDXDISKSyuXHb.jpg",
    title: "Jutarnja izmaglica",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Nostalgično",
    description: "Vijugavi zemljani put nestaje u zlatnoj jutarnjoj izmaglici, dok pozadinsko osvetljenje svodi udaljene brežuljke na meke, slojevite siluete.",
    orientation: "landscape",
  },
  {
    id: "IMG_4297",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ZgzxovAkdATTJSPA.jpg",
    title: "Labudovi kod tornja",
    category: "Divlja priroda",
    season: "Jesen",
    mood: "Mirno",
    description: "Par belih labudova odmara na mirnom ribnjaku ispred trošne drvene lovačke čeke, dok toplo jesensko lišće uokviruje scenu u zlatu.",
    orientation: "portrait",
  },
  {
    id: "IMG_5918",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/EyicaeNlRnghJcbX.jpg",
    title: "Ribarev put",
    category: "Dokumentarno",
    season: "Zima",
    mood: "Usamljeno",
    description: "Usamljena figura sa štapom za pecanje hoda po ogromnom snežnom nasipu, ostavljajući trag stopala u neokrnjenoj beloj površini.",
    orientation: "portrait",
  },
  {
    id: "IMG_3633",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/xqQmuZekkfniLFjk.jpg",
    title: "Vinograd u magli",
    category: "Pejzaž",
    season: "Jesen",
    mood: "Eterično",
    description: "Redovi vinograda konvergiraju ka maloj farmi pre nego što nestanu u gustoj magli, geometrijska preciznost redova rastvara se u misteriji.",
    orientation: "portrait",
  },
  {
    id: "IMG_5979",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/uJxvzbUaQIPVYJUx.jpg",
    title: "Vrana u zimi",
    category: "Divlja priroda",
    season: "Zima",
    mood: "Melanholično",
    description: "Usamljena vrana sedi na gredi prekrivenoj snegom koja se pruža nad zaleđenom rekom, maglovita pozadina svodi svet na studiju u bledom sivom.",
    orientation: "landscape",
  },
  {
    id: "IMG_5876",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/xAfKzPjaznuUqZiN.jpg",
    title: "Plava šuma",
    category: "Zima",
    season: "Zima",
    mood: "Čarobno",
    description: "Šuma opterećena snegom sija u dubokom plavom sumraku, skriveni izvor svetlosti baca eterično osvetljenje kroz snegom natovljene grane.",
    orientation: "landscape",
  },
  {
    id: "IMG_4047",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/ZnOMuIyDELUVavyv.jpg",
    title: "Mala voda",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Ekološki",
    description: "Gledano odozgo, dve sitne figure istražuju otkrivene sprudove reke sa niskim vodostanjem, organski oblici peska i vode stvaraju apstraktni pejzaž.",
    orientation: "landscape",
  },
  {
    id: "IMG_3573",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/TKBEKUzrJzAMbvgv.jpg",
    title: "Čelični most u sumrak",
    category: "Arhitektura",
    season: "Leto",
    mood: "Nostalgično",
    description: "Geometrijski čelični luk starog mosta uokviruje zlatni zalazak sunca, strukturni elementi bacaju duge senke po kaldrmi.",
    orientation: "landscape",
  },
  {
    id: "IMG_5559",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/GodNxIchzTSJKLwQ.jpg",
    title: "Zaleđeni potok",
    category: "Zima",
    season: "Zima",
    mood: "Spokojno",
    description: "Zaleđeni potok vijuga kroz pejzaž prekriven snegom, tamne siluete golih stabala ogledaju se u ledeno plavoj površini.",
    orientation: "landscape",
  },
  {
    id: "IMG_0554",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/cxBQadkptloTzoVI.jpg",
    title: "Ispucala zemlja",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Ekološki",
    description: "Majka i dete hodaju po ogromnom ispucalom dnu jezera, geometrijski uzorci suve blate protežu se do horizonta pod jarkim letnjim nebom.",
    orientation: "landscape",
  },
  {
    id: "IMG_3127",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/WqiRIqUMcXcfzMTV.jpg",
    title: "Ljuljanje nad rekom",
    category: "Dokumentarno",
    season: "Leto",
    mood: "Veselo",
    description: "Mlad čovek se ljulja sa grane drveta nad rekom dok drug posmatra iz čamca ispod, scena uhvaćena kroz atmosfersku letnju izmaglicu.",
    orientation: "portrait",
  },
  {
    id: "IMG_3071",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/qPkfyaAXGuFEqHuV.jpg",
    title: "Slojevi uz reku",
    category: "Arhitektura",
    season: "Leto",
    mood: "Posmatrački",
    description: "Biciklista na nasipu iznad kućnog broda stvara studiju horizontalnih slojeva — put, voda, brod i nebo složeni u precizne pojaseve.",
    orientation: "portrait",
  },
  {
    id: "IMG_4032",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/FWKhXrphUMSWTlEf.jpg",
    title: "Prazna klupa",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Kontemplativno",
    description: "Usamljena klupa stoji na peščanoj obali reke, njena samoća pojačana ogromnom otvorenom vodom i dijagonalnom linijom obale.",
    orientation: "landscape",
  },
  {
    id: "IMG_2954",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/UnAhSjuOOSAyhMYx.jpg",
    title: "Čaplja na ruševinama",
    category: "Divlja priroda",
    season: "Leto",
    mood: "Mirno",
    description: "Siva čaplja sedi na vrhu trošnog betonskog stuba obraslim žutim lišajem, nadgledajući reku sa svog uzvišenog mesta.",
    orientation: "landscape",
  },
  {
    id: "IMG_4825",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/MYxbPDJnqfSePtqR.jpg",
    title: "Pas na stazi",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Intimno",
    description: "Mali pas trči prema kameri duž šumske staze posute lišćem, bokeh-omekšana stabla stvaraju toplu, intimnu atmosferu.",
    orientation: "portrait",
  },
  {
    id: "IMG_5070_DxO",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663357937522/JRaAEmHGIyLEHtqH.jpg",
    title: "Jesenji portret",
    category: "Dokumentarno",
    season: "Jesen",
    mood: "Toplo",
    description: "Kontemplativni portret smešten u bogate teksture jeseni, topli tonovi sezone obavijaju subjekta u prirodnom svetlu.",
    orientation: "portrait",
  },
];

export const categories = ["Sve", "Pejzaž", "Divlja priroda", "Dokumentarno", "Zima", "Arhitektura"];

export const featuredPhotos = photos.filter(p => p.featured);
